CREATE TABLE [dbo].[Todos] (
TodoID BIGINT IDENTITY (1,1) NOT NULL,
Title VARCHAR (255) NOT NULL,
Description TEXT NULL,
Done BIT DEFAULT 0 NOT NULL,
IsDeleted BIT  DEFAULT 0 NOT NULL,
[InsertedDTM] DATETIME CONSTRAINT [DF_Todos_InsertedDTM] DEFAULT (sysdatetime()) NOT NULL,
CONSTRAINT [PK_Todos] PRIMARY KEY CLUSTERED ([TodoID] ASC)
)